current_weather.settings:
  type: config_object
  label: 'Current Weather configuration'
  mapping:
    city_name:
      type: label
      label: 'City name'
    country_code:
      type: label
      label: 'Country code'
    api_endpoint:
      type: label
      label: 'Openweathermap.org API endpoint'
    api_key:
      type: label
      label: 'Openweathermap.org API Key'
